name: ArtofEllioth
favicon: null
layout_spectrum: 0.10569
typography_spectrum: 0.59347
navigation:
  - name: About Me
    id: 41fcd3ff-925a-4e7e-9128-c896834aee37
    type: content
  - name: Blogs
    id: bd9a5f21-dd68-49bf-b671-85e4fc9776a9
    type: content
title: ArtofEllioth
description: Art/Drawing
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  brandStrength: 1
  lightness: 0
  saturation: 0.125
  rhythmicContrast: 0
purpose: []
