name: ArtofEllioth
favicon: null
layout_spectrum: 1
typography_spectrum: 0.60437
navigation:
  - name: About Me
    id: 41fcd3ff-925a-4e7e-9128-c896834aee37
    type: content
title: ArtofEllioth
description: Art/Drawing
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  brandStrength: 1
  lightness: 0.3125
  saturation: 0.6875
  rhythmicContrast: 0.4685552716255188
purpose: []
