typography_spectrum: 0.59347
color:
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  brandStrength: 1
  lightness: 0
  saturation: 0.125
  rhythmicContrast: 0
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: null
  facebook: null
  twitter: null
name: ArtofEllioth
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: About Me
    id: 41fcd3ff-925a-4e7e-9128-c896834aee37
    type: content
  - name: Pofolio
    id: f986d2cb-a778-4476-bea3-451018763686
    type: content
favicon: null
title: ArtofEllioth
description: Art/Drawing
purpose: []
